apiVersion: v1
kind: List
items:

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: kritis-clusterrolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - kind: ServiceAccount
    namespace: default
    name: default

# to let the admission server read imagewhitelist/imagesecuritypolicies
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: kritis-clusterrole
    labels:
      # Add these permissions to the "admin" default role, so that "admin" can see our CRD.
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
  rules:
  - apiGroups: ["kritis.grafeas.io"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch", "approve"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/approve"]
    verbs: ["update"]
  