apiVersion: v1
kind: Service
metadata:
  name: kritis-validation-hook
  labels:
    app: kritis-validation-hook
spec:
  ports:
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: kritis-validation-hook
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kritis-validation-hook
  labels:
    app: kritis-validation-hook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kritis-validation-hook
  template:
    metadata:
      labels:
        app: kritis-validation-hook
    spec:
      containers:
      - name: kritis-server
        image: gcr.io/priya-wadhwa/kritis-server
        imagePullPolicy: Always
        args: ["--tls-cert-file=/var/tls/tls.crt", "--tls-key-file=/var/tls/tls.key"]
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
        - mountPath: /var/tls
          name: tls
      volumes:
        - name: tls
          secret:
            secretName: tls-image-signature-webhook 
---
