apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.servicename }}
  labels:
    app: {{ .Values.servicename }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.gcrsecretname }}
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--tls-cert-file=/var/serving-cert/tls.crt"
            - "--tls-key-file=/var/serving-cert/tls.key"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
          readinessProbe:
            httpGet:
              path: /
              port: https
        volumeMounts:
        - mountPath: /var/serving-cert
          name: tls
        volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tlssecretname }}
