apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kritis.servicename" . }}
  labels:
    app: {{ template "kritis.servicename" . }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kritis.servicename" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kritis.servicename" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Servicename }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
              - "--tls-cert-file=/var/serving-cert/tls.crt"
              - "--tls-key-file=/var/serving-cert/tls.key"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
          readinessProbe:
            httpGet:
              path: /
              port: https
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
        volumeMounts:
            - mountPath: /var/serving-cert
              name: tls
        volumes:
          - name: tls
            secret:
              secretName: {{ template "kritis.secretname" . }}
