# Default values for kritis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/kritis-project/kritis-server
  tag: v0.0.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceName: kritis-validation-hook
serviceNamePods: kritis-validation-hook
serviceNameDeployments: kritis-validation-hook-deployments
tlsSecretName: tls-webhook-secret
csrName: tls-webhook-secret-cert
cronInterval: 1h

image:
  repository: gcr.io/kritis-project/kritis-server
  tag: v0.0.1
  name: kritis-server
  pullPolicy: Always

# kritis-server-webhook.yaml values
caBundle: ""
serviceNamespace: "default"

gacSecret:
  name: "gac-ca-admin"
  path: "gac.json"

preinstall:
  serviceAccount: "kritis-preinstall-serviceaccount"
  clusterRoleBinding: "kritis-preinstall-clusterrolebinding"
  createNewCSR: "--create-new-csr=true"
  installCRDs: "--install-crds=true"
  pod:
    name: "kritis-preinstall"
    image: "gcr.io/kritis-project/preinstall:v0.0.1"
    command: ["/preinstall"]

postinstall:
  pod:
    name: "kritis-postinstall"
    image: "gcr.io/kritis-project/postinstall:v0.0.1"
    command: ["/postinstall"]


predelete:
  deleteCSR: "--delete-csr=true"
  deleteCRDs: "--delete-crd=true"
  pod:
    name: "kritis-predelete"
    image: "gcr.io/kritis-project/predelete:v0.0.1"
    command: ["/predelete"]
