apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.kritis.grafeas.io
spec:
  group: kritis.grafeas.io
  version: v1beta1
  scope: Cluster
  names:
    plural: configs
    singular: config
    kind: KritisConfig
